#!/bin/sh

set -e


case "$1" in
    install)
        mkdir /etc/growiot -p
        ;;

    upgrade|abort-upgrade)
        systemctl stop ms-01-azure-gateway.service
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

exit 0
