name: docker
on:
  push:
  workflow_dispatch:


jobs:
  build_01:
    name: Build Pi Compiler Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: Docker login 
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin 
      
      - name: Build image and push
        run: | 
          docker build -t fabianbruenger/greeniot4all:latest -f firmware/raspberry-pi-zero-w/utils/Dockerfile .
          # IMAGE_ID=$( docker images --filter=reference=greeniot4all/pi-compiler --format "{{.ID}}" )
          # docker tag $IMAGE_ID greeniot4all.jfrog.io/greeniot4all-docker-local/pi-compiler:latest
          docker push fabianbruenger/greeniot4all:latest