name: Docker
on:
  push:
  workflow_dispatch:


jobs:
  build_01:
    name: Build Pi Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: Docker login 
        run: docker login greeniot4all.jfrog.io -u ${{ secrets.JFROG_USER }} -p ${{ JFROG_PASSWORD }}