name: Docker
on:
  # push:
  workflow_dispatch:


jobs:
  build_01:
    name: Build Pi Compiler Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: Docker login 
        run: echo ${{ secrets.JFROG_PASSWORD }} | docker login greeniot4all.jfrog.io -u ${{ secrets.JFROG_USER }} --password-stdin 
      
      - name: Build image and push
        run: | 
          docker build -t greeniot4all/pi-compiler:latest -f firmware/raspberry-pi-zero-w/utils/Dockerfile .
          docker push greeniot4all.jfrog.io/greeniot4all-docker-local/pi-compiler:latest